"""Generate csrc/crown6_tanhlut.h -- frozen tanh LUT for the CROWN6 MLP wire spec.

Resolution of the mandated C-vs-torch/numpy cross-check 1-ulp divergence:
numpy's vectorized tanh and C libm tanh differ by 1 ulp on some inputs
(e.g. pre=19.0612793 -> 1.0 vs 1-2^-53), which flips int-rounded predictions
at knife-edge .5 boundaries (~916/2M px with extreme random weights).
Fix: BOTH sides index this frozen table (identical constants), so h bits are
identical by construction; the xcheck then proves 0 mismatches.

Table: tanh on [0,8] at step 2^-12 (32769 entries, correctly-rounded double
literals %.17g -> parse back bit-exactly). Wire rule: r=|pre|*4096 (exact);
r>32768 -> h=+/-1.0; else idx=floor(r+0.5), h=sign(pre)*T[idx].
Fidelity: input quantization <= 2^-13 -> h err <= 1.3e-4 -> output err ~1e-3
gray (measured ratio impact: negligible, gates use the same path).
"""
import math
import os

STEP = 12
N = 8 * (1 << STEP) + 1  # 32769

lines = []
lines.append("/* FROZEN tanh LUT for CROWN6 MLP wire spec. Generated by gen_tanhlut.py; DO NOT EDIT.")
lines.append(" * T[i] = tanh(i/4096) on [0,8], %.17g double literals (bit-exact round-trip).")
lines.append(" * Rule: r=|pre|*4096 (exact); r>32768 -> +/-1.0; else h=sign*T[(int)floor(r+0.5)]. */")
lines.append("#pragma once")
lines.append(f"#define C6_TANH_N {N}")
lines.append("static const double C6_TANH[32769] = {")
row = []
for i in range(N):
    row.append("%.17g" % math.tanh(i / 4096.0))
    if len(row) == 4 or i == N - 1:
        lines.append("  " + ", ".join(row) + ("," if i < N - 1 else ""))
        row = []
lines.append("};")
out = os.path.join("/tmp/opencode/autocompress/csrc", "crown6_tanhlut.h")
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", out, N, "entries")
